name: Proxy Workflow

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger Workflows in cicd/.github/workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for workflow in cicd/.github/workflows/*.yml; do
            workflow_name=$(basename $workflow)
            gh workflow run "$workflow_name"
          done

